spring.application.name=user-service

spring.datasource.url=jdbc:mysql://localhost:3306/team_task_management
spring.datasource.username=root
spring.datasource.password=Giabao1309
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port= 1309
